# Generated by Django 3.2 on 2021-05-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0003_account_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='image',
            field=models.ImageField(default='userdefault.png', help_text='Upload a post image', upload_to='images/', verbose_name='image'),
        ),
    ]
