# Generated by Django 3.2 on 2021-05-13 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0007_alter_account_approvals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='approvals',
        ),
    ]
