# Generated by Django 3.2 on 2021-05-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0009_alter_account_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='photo',
            field=models.ImageField(default='/images/userdefault.png', upload_to='', verbose_name='user_image'),
        ),
    ]
