# Generated by Django 3.2 on 2021-05-13 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_alter_approval_name'),
        ('customuser', '0010_account_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='Comments',
            field=models.ManyToManyField(blank=True, to='backend.Comment'),
        ),
        migrations.AddField(
            model_name='account',
            name='Declines',
            field=models.ManyToManyField(blank=True, to='backend.Decline'),
        ),
    ]
