# Generated by Django 3.2 on 2021-05-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_alter_approval_name'),
        ('customuser', '0011_auto_20210514_0001'),
    ]

    operations = [

    ]
