# Generated by Django 3.2 on 2021-05-13 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0012_account_approvals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='Comments',
        ),
        migrations.RemoveField(
            model_name='account',
            name='Declines',
        ),
    ]
