# Generated by Django 3.2 on 2021-05-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_alter_approval_name'),
        ('customuser', '0014_auto_20210514_0009'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='account',
        #     name='Approvals',
        #     field=models.ManyToManyField(blank=True, to='backend.Approval'),
        # ),
    ]
