# Generated by Django 3.2 on 2021-05-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_auto_20210514_1523'),
        ('customuser', '0015_account_approvals'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='account',
        #     name='Approvals',
        #     field=models.ManyToManyField(blank=True, to='backend.Approval'),
        # ),
    ]
