# Generated by Django 3.2 on 2021-05-20 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_auto_20210520_2250'),
        ('customuser', '0019_alter_account_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='Approvals',
            field=models.ManyToManyField(blank=True, to='backend.Approval'),
        ),
    ]
