# Generated by Django 3.2 on 2021-04-26 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('PostId', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('PublishDate', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('Title', models.TextField(max_length=100)),
                ('Text', models.TextField()),
                ('Photo', models.CharField(max_length=50, unique=True)),
                ('Tags', models.TextField()),
                ('Category', models.CharField(max_length=30)),
                ('ObjectionTo', models.UUIDField(editable=False)),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
