# Generated by Django 3.2 on 2021-04-27 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='ObjectionTo',
            field=models.UUIDField(default='00000000-0000-0000-0000-000000000000'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='Tags',
            field=models.TextField(max_length=60),
        ),
    ]
