# Generated by Django 3.2 on 2021-05-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210427_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='Image',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
        ),
    ]
