# Generated by Django 3.2 on 2021-05-09 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_posts_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='Photo',
        ),
        migrations.CreateModel(
            name='PostImages',
            fields=[
                ('PhotoId', models.AutoField(primary_key=True, serialize=False)),
                ('Image', models.ImageField(default='images/default.png', help_text='Upload a post image', upload_to='images/', verbose_name='image')),
                ('Post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_image', to='backend.posts')),
            ],
        ),
    ]
