# Generated by Django 3.2 on 2021-05-09 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20210509_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='Image',
        ),
    ]
