# Generated by Django 3.2 on 2021-05-09 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_remove_posts_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postimages',
            options={'verbose_name': 'Post Image', 'verbose_name_plural': 'Post Images'},
        ),
        migrations.RenameField(
            model_name='postimages',
            old_name='Image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='postimages',
            old_name='Post',
            new_name='post',
        ),
    ]
