# Generated by Django 3.2 on 2021-05-11 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20210511_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='Photo',
        ),
    ]
