# Generated by Django 3.2 on 2021-05-11 16:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_remove_posts_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='Photo',
            field=models.ImageField(default='/images/default.png', upload_to='', verbose_name='post_image'),
        ),
        migrations.AddField(
            model_name='posts',
            name='PublishDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date joined'),
            preserve_default=False,
        ),
    ]
