# Generated by Django 3.2 on 2021-05-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='Comments',
            field=models.ManyToManyField(to='backend.Comment'),
        ),
    ]
