# Generated by Django 3.2 on 2021-05-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_alter_approval_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='Approvals',
            field=models.ManyToManyField(blank=True, to='backend.Approval'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='Comments',
            field=models.ManyToManyField(blank=True, to='backend.Comment'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='Declines',
            field=models.ManyToManyField(blank=True, to='backend.Decline'),
        ),
    ]
