# Generated by Django 3.2 on 2021-05-13 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_auto_20210513_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approval',
            name='post',
        ),
        migrations.RemoveField(
            model_name='approval',
            name='uuid',
        ),
    ]
