# Generated by Django 3.2 on 2021-05-13 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_auto_20210513_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approval',
            name='user',
        ),
    ]
