# Generated by Django 3.2 on 2021-05-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_auto_20210513_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='Approvals',
            field=models.ManyToManyField(blank=True, to='backend.Approval'),
        ),
    ]
