# Generated by Django 3.2 on 2021-05-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_alter_approval_name'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='approval',
        #     name='name',
        #     field=models.CharField(default='', max_length=200, unique=True),
        # ),
    ]
