# Generated by Django 3.2 on 2021-05-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_auto_20210514_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='decline',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
