# Generated by Django 3.2 on 2021-05-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_auto_20210514_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='Photo',
            field=models.ImageField(default='default.png', upload_to='', verbose_name='post_image'),
        ),
    ]
