# Generated by Django 3.2 on 2021-05-20 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_auto_20210520_2250'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='posts',
        #     name='PostPhoto',
        #     field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image'),
        #     preserve_default=False,
        # ),
    ]
