# Generated by Django 3.2 on 2021-05-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_posts_postphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='PostPhoto',
        ),
        migrations.AddField(
            model_name='posts',
            name='Photo',
            field=models.ImageField(default='default.png', upload_to='', verbose_name='post_image'),
        ),
    ]
