# Generated by Django 3.2 on 2021-05-28 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_auto_20210524_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='Objections',
            field=models.ManyToManyField(blank=True, to='backend.Posts'),
        ),
    ]
